### ISSUE TITLE
Bug in ELFIO/elfio/elfio_relocation.hpp

### ISSUE THREAD

**Issue by rrr9rrr** [serge1/ELFIO#146] opened 2024-12-07 19:32 UTC
ERROR MESSAGE:

[ 65%] Building CXX object CMakeFiles/converter.dir/src/elfio_connector.cpp.o
/home/spaceenotik/src/elf-converter/src/elfio_connector.cpp: In function ‘std::vector<std::shared_ptr<RelocationSection> > {anonymous}::getRelocationSections(ELFIO::elfio&, std::unordered_map<short unsigned int, std::shared_ptr<Section> >, std::unordered_map<unsigned int, std::shared_ptr<Symbol> >)’:
/home/spaceenotik/src/elf-converter/src/elfio_connector.cpp:104:88: error: invalid conversion from ‘unsigned char*’ to ‘unsigned int’ [-fpermissive]
  104 |                 bool ret = relocationSectionAccessor.get_entry(i, offset, symbolIndex, &type, addend);
      |                                                                                        ^~~~~
      |                                                                                        |
      |                                                                                        unsigned char*
In file included from /home/spaceenotik/src/elf-converter/dependencies/elfio/elfio/elfio.hpp:1063,
                 from /home/spaceenotik/src/elf-converter/src/elf.h:4,
                 from /home/spaceenotik/src/elf-converter/src/elfio_connector.h:4,
                 from /home/spaceenotik/src/elf-converter/src/elfio_connector.cpp:1:
/home/spaceenotik/src/elf-converter/dependencies/elfio/elfio/elfio_relocation.hpp:89:33: note:   initializing argument 4 of ‘bool ELFIO::relocation_section_accessor_template<S>::get_entry(ELFIO::Elf_Xword, ELFIO::Elf64_Addr&, ELFIO::Elf_Word&, unsigned int&, ELFIO::Elf_Sxword&) const [with S = ELFIO::section; ELFIO::Elf_Xword = long unsigned int; ELFIO::Elf64_Addr = long unsigned int; ELFIO::Elf_Word = unsigned int; ELFIO::Elf_Sxword = long int]’
   89 |                     unsigned&   type,
      |                     ~~~~~~~~~~~~^~~~
/home/spaceenotik/src/elf-converter/src/elfio_connector.cpp:104:88: error: cannot bind rvalue ‘(unsigned int)(& type)’ to ‘unsigned int&’
  104 |                 bool ret = relocationSectionAccessor.get_entry(i, offset, symbolIndex, &type, addend);
      |                                                                                        ^~~~~
make[2]: *** [CMakeFiles/converter.dir/build.make:202: CMakeFiles/converter.dir/src/elfio_connector.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:513: CMakeFiles/converter.dir/all] Ошибка 2
make: *** [Makefile:156: all] Ошибка 2

WHAT TO DO:
In file, EFFIO/elfio/elfio_relocation.hpp:89, replace:
unsigned&   type,
TO:
unsigned int  type,
AND IT WOULD COMPILE.

**Comment by serge1** [comment] 2024-12-09 05:28
Both function "getRelocationSections" and file "../elf-converter/src/elfio_connector.cpp" don't belong to ELFIO library. If you feel that the problem is related to ELFIO library, please provide more information on how the issue can be reproduced

**Comment by serge1** [comment] 2024-12-15 07:44
Due to the lack of communication, I am closing this issue. Please reopen if you feel so

**Closed by serge1** 2024-12-15 07:44 UTC
