### ISSUE TITLE
load and validate file, no issues, save same unmodified one leads to issues

### ISSUE THREAD

**Issue by arne123** [serge1/ELFIO#126] opened 2023-08-25 12:35 UTC
I just discovered an issue where saving an unmodified file leads to an issue.
Validate does not report anything, but saving fails here:

https://github.com/serge1/ELFIO/blob/main/elfio/elfio.hpp#L869

                if ( req_offset < cur_offset ) {
                    // something has gone awfully wrong, abort!
                    // section_align would turn out negative, seeking backwards and overwriting previous data

all I am doing is

    reader.load("demo.elf");
    std::cout << reader.validate();
    reader.save("new_file.elf");

[demo.tar.gz](https://github.com/serge1/ELFIO/files/12439083/demo.tar.gz)

any Idea about that?

**Comment by serge1** [comment] 2023-08-28 16:45
Hi,

Thank you for providing an example file. It is interesting and I am wondering what is confusing the library.
In general case, the scenario of loading and saving may not always work. Please see the thread #74 and the last statement in https://github.com/serge1/ELFIO/wiki/How-to-modify-section-data.

Best regards

**Comment by arne123** [comment] 2023-08-28 22:07
Thanks for the hints. 
In order to prevent any remapping of the file I want just to change the content of an existing section, not changing its size.
Anyhow, I was expecting that the validation applies same checks as saving, but seems not.
I know that this file makes use of different physical and virtual Addresses.

**Comment by serge1** [comment] 2023-08-29 17:28
Definitely, the library does not support such configuration. I am not aware of a generic way to support it. So, you may tweak the sources and update the calculations. Alternatively, in condition that it is a commonly used architecture, you may send me a link to a description of its ABI.

**Comment by arne123** [comment] 2023-08-29 21:04
Found this:
https://www.ti.com/lit/pdf/sprac71

"However, for the C28x ELF format, fields that represent target addresses are native (word-oriented), but fields
that represent target sizes are expressed in bytes."

**Comment by serge1** [comment] 2024-03-03 15:02
The issue is opened for a long time. I am not familiar with the features of this specialized architecture and without external help or explanation will not be able to support it.
So, I am closing the issue. Please reopen if new information is available or external help is found.

**Closed by serge1** 2024-03-03 15:02 UTC
