### ISSUE TITLE
Loaded, modified, saved elf file is more different than expected from original

### ISSUE THREAD

**Issue by sktpin** [serge1/ELFIO#63] opened 2021-01-14 18:07 UTC
Hello, I'm don't know a lot of details about the .elf format, so maybe there can be a good reason for it.

I have a bare metal project for ARM Cortex M, using the ARM GCC compiler toolchain for that.
So I use ELFIO load a produced .elf file, search for one section by name, call set_data() on that section to change the content (size should remain the same), and call .save() on that elfio object.
The changed section is only a few uint32's big.

Looking at the resulting file in the hex editor, I find things like big blocks (kilobytes maybe) of zeroes where the original file had data.
Also, the saved file is now 6KB bigger than the original one.

Can there be legitimate reasons for these observations, or is something wrong? (I've not tried using it yet)

**Comment by serge1** [comment] 2021-01-15 15:58
Duplicate of #62

**Closed by serge1** 2021-01-15 15:58 UTC
